INICIAR
  Definir punto1 como Punto : 
  a coordenada x de punto1 asignar 1 : 
  a coordenada y de punto1 asignar 1 : 

  Definir hiperbola1 como Hiperbola : 
  a centro de hiperbola1 asignar punto1 : 
  a semiEje A de hiperbola1 asignar 2 : 
  a semiEje B de hiperbola1 asignar 3 : 
Rotar hiperbola1 hasta 30 grados : 
  Trasladar en x hiperbola1 hasta -3 unidades : 
  Trasladar en y hiperbola1 hasta 5 unidades : 
  Colorear borde de hiperbola1 de verde :
  Dibujar hiperbola1 : 

FINALIZAR

