INICIAR
  Definir punto1 como punto:
  Definir punto2 como punto:
  Definir punto3 como punto:
  Definir triangulo1 como trinagulo:
  punto1 coordenada x asignar 1:
  punto1 coordenada y asignar 1:
  punto2 coordenada x asignar 2:
  punto2 coordenada y asignar 2:
  punto3 coordenada x asignar 3:
  punto3 coordenada y asignar 1:
  triangulo1 vertice a asignar punto1:
  triangulo1 vertice b asignar punto2:
  triangulo1 vertice c asignar punto3:  
  Dibujar triangulo1:
FINALIZAR
